`pandera` + `pyarrow` tests x 1.
This commit is the first (and hopefully last) in a commit chain
attempting to resolve spurious test failures raised by `pandera`, which
now *effectively* appears to require `pyarrow` despite `pyarrow`
supposedly being a technically optional runtime dependency of `pandera`.
If `pyarrow` is *not* installed, modern versions of `pandera` now raise
exceptions from the @beartype test suite despite tests neither
referencing nor requiring `pyarrow`-specific dtypes resembling:

```python
TypeError: pyarrow must be installed to use pyarrow dtypes.
```

It is saddening. (*Gladly maddening!*)