`jakebailey/pyright-action` x 2.
This commit is the next (and hopefully last) in a commit chain
attempting to resolve a recent spate of spurious issues pertaining to
@jakebailey's otherwise stellar GitHub Action
`jakebailey/pyright-action`. That Action worked *great* for literally
years, until timeouts started cropping up under Windows resembling:

```
Running: c:\\runners\\2.317.0\\externals\\node20\\bin\\node.exe
C:\\hostedtoolcache\\windows\\pyright\\1.1.369\\x64\\package\\index.js
--pythonversion 3.11 --outputjson
Error: The operation was canceled.
```

The culprit is `pyright 1.1.369`, which fundamentally broke pyright so
badly that pyright no longer terminates when pointed at the @beartype
codebase. An infinite loop in a static type-checker basically makes that
static type-checker a Denial of Service (DOS) attack vector and
therefore a Common Vulnerability and Exploit (CVE) waiting to happen. I
can't believe Microsoft broke pyright so badly that's it basically a
self-inflicting DoS now. So not pleased, Microsoft.

This commit purports to resolve this issue with finality by:

* Restoring @jakebailey's stellar GitHub Action
  `jakebailey/pyright-action` in our continuous integration (CI)
  workflow.
* Pinning pyright to `pyright 1.1.365`, the most recent version known to
  behave well.

(*Bobble-headed bubble in a bed!*)