Add `mypy.ini` to sdist to fix running tests
Include `mypy.ini` in sdist archives in order to fix test failure
caused by it being missing:

    FAILED ../../../beartype_test/a90_func/pep/test_pep561_static.py::test_pep561_mypy - beartype.roar.BeartypeTestPathException: File "/tmp/beartype/dist/beartype-0.13.1/mypy.ini" not found.