Avoid static type checking error in mock types FAQ example
If I use the example code without this change, I get the following errors from `mypy` and `pyright`:

```
error: Read-only property cannot override read-write property  [misc]
```

```
error: "__class__" incorrectly overrides property of same name in class "object"
    Property method "fset" is missing in override (reportIncompatibleMethodOverride)
```