`Generic[T]` + (`NamedTuple` | `TypedDict`) x 8.
This commit is the last in a commit chain resolving an *extremely*
subtle harmful interaction between **generics** (i.e., types
subclassing the PEP 484- and 585-compliant `typing.Generic` superclass),
**typed dictionaries** (i.e., PEP 589-compliant `typing.TypedDict`
subclasses), and **named tuples** (i.e., PEP 484-compliant
`typing.NamedTuple` subclasses), resolving issue #519 kindly submitted
by CMU ECE my-gods-so-many-cool-acronyms-guy @thetianshuhuang (Tianshu
Huang). Specifically, this commit gives up entirely after fully
supporting this feature on @beartype's end. Why? Because...

CPython fails to fundamentally support this. CPython prohibits
`TypedDict` subclasses from being type-checked at runtime. This means
that **generic typed dictionaries** (i.e., types subclassing both
`TypedDict` *and* `Generic`) are not runtime type-checkable. That's
awful!

## Behold. CPython Hates Generic Typed Dictionaries.

```python
>>> from typing import Generic, TypeVar, TypedDict, NamedTuple
>>> class Foo[T](TypedDict, Generic[T]):
...     bar: T

# *THIS SHOULD WORK.* Sadly, CPython hates us.
>>> isinstance(Foo(), Foo)
Traceback (most recent call last):
  File "/home/leycec/tmp/mopy.py", line 13, in <module>
    isinstance(Foo(), Foo)
    ~~~~~~~~~~^^^^^^^^^^^^
  File "/home/leycec/py/pyenv/versions/3.13.2/lib/python3.13/typing.py", line 3235, in __subclasscheck__
    raise TypeError('TypedDict does not support instance and class checks')
TypeError: TypedDict does not support instance and class checks
```

Because `TypedDict` prohibits instance and class checks, `TypedDict`
subclasses (including generic typed dictionaries) also prohibit instance
and class checks. But that's exactly how runtime type-checkers check
types! If you attempt to use a generic typed dictionary as a type hint,
@beartype now explicitly tells you that CPython prohibits what you want
to do:

```python
beartype.roar.BeartypeDecorHintPep3119Exception: Function __main__.baz() parameter
"x" wrapper parameter <class '__main__.Foo'> uncheckable at runtime (i.e., not
passable as second parameter to isinstance(), due to raising "TypeError: TypedDict
does not support instance and class checks" from metaclass
_TypedDictMeta.__instancecheck__() method).
```

As far as I know, this is a bug. It's unlikely that CPython devs
actually intended to render generic typed dictionaries incompatible with
@beartype, @pydantic, and `typeguard` – but that's what they did.

@beartype: *Even when our best isn't good enough, we do our best.*

(*Untimely temerity!*)