Throw shade at bad boi callables.
This commit improves the readability of exceptions raised by edge-case
`@beartype`-decorated callables annotated by one or more forward
references while also failing to define the `__module__` dunder
attribute, resolving issue #381 kindly submitted by dynamical Bostonian
and bonafide real-life main character @femtomc (McCoy R. Becker). For
unknown (and probably indefensible) reasons, the third-party
`markdown-exec` package appears to define such horrifying callables.
When confronted with such horrifying callables, the `@beartype`
decorator now raises human-readable exceptions resembling:

```python
beartype.roar.BeartypeDecorHintForwardRefException: Function muh_func()
parameter "muh_arg" forward reference type hint "MuhType" unresolvable,
as "muh_func.__module__" dunder attribute undefined (e.g., due to
<function muh_func at 0x7f030d402160> being defined only dynamically
in-memory). So much bad stuff is happening here all at once that
@beartype can no longer cope with the explosion in badness.
```

Flex those burly exception messages, @beartype! Flex 'em! (*A flexible lexicon on iconic nicks!*)