Expose beartype's `__all__`
Mypy is unhappy because beartype isn't explicitly specifying its exported attributes. I assume this is a mistake since this code is not deleted but commented out.

```
error: Module "beartype" does not explicitly export attribute "beartype"; implicit reexport disabled
```