Mypy + vale false positives resolved.
This commit resolves a long-standing integration issue when subjecting
beartype to static type checking by a static type checker that is almost
certainly mypy. Previously, mypy erroneously emitted one error for each
otherwise valid beartype validator: e.g.,

``` bash
$ mypy
error: The type "Type[IsAttr]" is not generic and not indexable  [misc]
```

Mypy and presumably other static type checkers now no longer do so,
substantially improving the usability of downstream packages leveraging
both static type checking *and* beartype validators.

Unrelatedly, this commit also streamlines exception message handling
throughout the codebase. (*Multigenerational genera!*)