`BeartypeHintOverrides` + CPython 3.12.0 + Windows.
This commit *possibly* resolves a subtle issue with respect to obsolete
versions of CPython 3.12.0 under Windows, *possibly* resolving oddball
issue #399 kindly submitted by @denballakh whose avatar is the adorable
green frog. For unknown reasons, @beartype 0.18.5 raises the following
exception at importation time for @denballakh:

```python
beartype.roar.BeartypeHintOverridesException: Recursive type hint
override float: typing.Union[float, int] currently unsupported. Please
complain on our friendly issue tracker if you feel that this is dumb:
    https://github.com/beartype/beartype/issues
```

Unfortunately for @denballakh, the 50,000-line @beartype
test suite of doom currently passes under CPython 3.12.4 + Windows 10.
Weird, huh? Since I can't replicate this issue, I can't resolve this
issue. That said, I *did* muck about in the codebase in a dangerous
manner that might address this subtle issue. Fingers are crossed. Breath
is bated. Let's pretend I did something meaningful today. (*Until tilling!*)