Remove incorrect `self` argument from `mock_types` example
Without this change, running the example gives:

```
TypeError: muh_func() missing 1 required positional argument: 'muh_arg'
```